//! `ibkr_place_order` Tauri command. Surveillance-plus-confirmed-execution
//! (master Hard Invariant 1): every parent order goes through this
//! command with explicit human confirmation in our UI. Phase 2
//! extends the command to record an `OrderIntent` row before the
//! order hits IBKR — that's how a fill later carries the `setup_id`
//! it answered, and the slippage attribution against `intended_price`.
//!
//! When `setup_id` is absent the command still places the order (the
//! UI may issue an order without a setup link; the fill ends up in
//! the "unattributed" attribution bucket). When `setup_id` is given
//! the command resolves the trader's account, generates a unique
//! `intent_id`, and lands the row through `TcaService::record_intent`
//! before forwarding to IBKR.

use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

use chrono::{NaiveDate, Utc};
use tauri::State;

use crate::ibkr::state::IbkrState;
use crate::ibkr::types::{IbkrExecution, OrderAction, OrderRequest, OrderType};
use crate::services::tca::{IntendedPriceSource, IntentSide, NewOrderIntent, TcaService};

#[tauri::command]
pub async fn ibkr_place_order(
    state: State<'_, IbkrState>,
    tca: State<'_, Arc<TcaService>>,
    order: OrderRequest,
    setup_id: Option<i64>,
    intended_price: Option<f64>,
) -> Result<i32, String> {
    // Best-effort intent record: a missing intended_price (and no
    // setup_id) means we have nothing to compare against and the
    // intent is skipped. The order itself proceeds either way —
    // surveillance-only is preserved.
    if let Some(price) = intended_price {
        let account = state
            .client
            .get_accounts()
            .await
            .map_err(|e| e.to_string())?
            .into_iter()
            .next()
            .ok_or_else(|| "no IBKR account available for intent recording".to_string())?;
        let intent = build_intent(&account, &order, setup_id, price);
        if let Err(e) = tca.inner().record_intent(intent).await {
            // Log-and-continue: a botched intent shouldn't block the
            // order. This branches cleanly into the "unattributed"
            // bucket; the trader still gets the fill.
            tracing::warn!(error = %e, "place_order: intent record failed; continuing");
        }
    }
    state
        .client
        .place_order(order)
        .await
        .map_err(|e| e.to_string())
}

fn build_intent(
    account: &str,
    order: &OrderRequest,
    setup_id: Option<i64>,
    intended_price: f64,
) -> NewOrderIntent {
    let now = Utc::now();
    let is_market = matches!(order.order_type, OrderType::Market);
    let window_minutes = if is_market { 5 } else { 60 };
    let intended_cents = (intended_price * 100.0).round() as i64;
    NewOrderIntent {
        intent_id: gen_intent_id(setup_id),
        setup_id,
        account: account.to_string(),
        symbol: order.symbol.clone(),
        side: match order.action {
            OrderAction::Buy => IntentSide::Buy,
            OrderAction::Sell => IntentSide::Sell,
        },
        qty: order.quantity,
        intended_price_cents: intended_cents.max(0),
        // The UI passes `intended_price` after sourcing it from the
        // setup trigger; when no setup, source is best-guess
        // `LimitPrice` for limit orders, `LiveQuote` otherwise. The
        // command itself is one layer above the source decision and
        // can't tell the difference, so default conservatively.
        intended_price_source: if setup_id.is_some() {
            IntendedPriceSource::TriggerPrice
        } else if matches!(order.order_type, OrderType::Limit) {
            IntendedPriceSource::LimitPrice
        } else {
            IntendedPriceSource::LiveQuote
        },
        posted_at: now,
        expires_at: now + chrono::Duration::minutes(window_minutes),
    }
}

/// Process-local monotonic counter so two intents recorded inside
/// the same nanosecond resolution don't collide. The combination of
/// `(unix_nanos, counter)` is unique per process; collisions across
/// processes are impossible because intents are only generated by
/// the running app, never by external clients.
static INTENT_COUNTER: AtomicU64 = AtomicU64::new(0);

fn gen_intent_id(setup_id: Option<i64>) -> String {
    let prefix = match setup_id {
        Some(id) => format!("intent_s{id}"),
        None => "intent_manual".to_string(),
    };
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let n = INTENT_COUNTER.fetch_add(1, Ordering::Relaxed);
    format!("{prefix}_{nanos}_{n}")
}

/// Parses a `YYYY-MM-DD` string into a `NaiveDate`, returning a typed error
/// for the Tauri command boundary. Extracted so it can be unit-tested without
/// constructing a Tauri `State`.
pub(crate) fn parse_date_arg(date: &str) -> Result<NaiveDate, String> {
    NaiveDate::parse_from_str(date, "%Y-%m-%d")
        .map_err(|e| format!("invalid date '{date}', expected YYYY-MM-DD: {e}"))
}

#[tauri::command]
pub async fn ibkr_get_executions(
    state: State<'_, IbkrState>,
    date: String,
) -> Result<Vec<IbkrExecution>, String> {
    let parsed = parse_date_arg(&date)?;
    state
        .client
        .executions(parsed)
        .await
        .map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ibkr::types::{OrderAction, OrderType};

    fn order(action: OrderAction, ty: OrderType) -> OrderRequest {
        OrderRequest {
            symbol: "AAPL".to_string(),
            action,
            quantity: 100.0,
            order_type: ty,
            price: Some(100.0),
        }
    }

    #[test]
    fn build_intent_market_order_uses_short_window() {
        let intent = build_intent(
            "DU1",
            &order(OrderAction::Buy, OrderType::Market),
            None,
            100.0,
        );
        let window = (intent.expires_at - intent.posted_at).num_minutes();
        assert!(window <= 5);
    }

    #[test]
    fn build_intent_limit_order_uses_long_window() {
        let intent = build_intent(
            "DU1",
            &order(OrderAction::Buy, OrderType::Limit),
            None,
            100.0,
        );
        let window = (intent.expires_at - intent.posted_at).num_minutes();
        assert!(window >= 60);
    }

    #[test]
    fn build_intent_setup_linked_uses_trigger_price_source() {
        let intent = build_intent(
            "DU1",
            &order(OrderAction::Buy, OrderType::Limit),
            Some(42),
            100.0,
        );
        assert_eq!(
            intent.intended_price_source,
            IntendedPriceSource::TriggerPrice
        );
        assert_eq!(intent.setup_id, Some(42));
    }

    #[test]
    fn build_intent_no_setup_limit_falls_to_limit_price_source() {
        let intent = build_intent(
            "DU1",
            &order(OrderAction::Sell, OrderType::Limit),
            None,
            100.0,
        );
        assert_eq!(
            intent.intended_price_source,
            IntendedPriceSource::LimitPrice
        );
        assert_eq!(intent.side, IntentSide::Sell);
    }

    #[test]
    fn build_intent_no_setup_market_falls_to_live_quote_source() {
        let intent = build_intent(
            "DU1",
            &order(OrderAction::Buy, OrderType::Market),
            None,
            100.0,
        );
        assert_eq!(intent.intended_price_source, IntendedPriceSource::LiveQuote);
    }

    #[test]
    fn build_intent_rounds_intended_price_to_cents() {
        let intent = build_intent(
            "DU1",
            &order(OrderAction::Buy, OrderType::Limit),
            None,
            100.504,
        );
        assert_eq!(intent.intended_price_cents, 10_050);
        let intent = build_intent(
            "DU1",
            &order(OrderAction::Buy, OrderType::Limit),
            None,
            100.506,
        );
        assert_eq!(intent.intended_price_cents, 10_051);
    }

    #[test]
    fn build_intent_clamps_negative_price_to_zero() {
        let intent = build_intent(
            "DU1",
            &order(OrderAction::Buy, OrderType::Limit),
            None,
            -5.0,
        );
        assert_eq!(intent.intended_price_cents, 0);
    }

    #[test]
    fn gen_intent_id_carries_setup_prefix() {
        let with_setup = gen_intent_id(Some(7));
        assert!(with_setup.starts_with("intent_s7_"));
        let manual = gen_intent_id(None);
        assert!(manual.starts_with("intent_manual_"));
    }
}
